Traceback (most recent call last):
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
integration_status = json_response["Data"]["IntegrationStatus"]
print(integration_status)

#integration status (Sent, Received,...)

if integration_status == "Sent":
    print ("Sent: Your invoice has been sucessfully processed ans set to your costummer.")
if integration_status == "Received":
    print ("Received: Your invoice has been received by your costummer.")
else:
    print("Your invoice integration status: " + integration_status);

#print(json.dumps(json_response, indent=4))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
[1;32m<ipython-input-15-d6780398c77f>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mintegration_status[0m [1;33m=[0m [0mjson_response[0m[1;33m[[0m[1;34m"Data"[0m[1;33m][0m[1;33m[[0m[1;34m"IntegrationStatus"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mprint[0m[1;33m([0m[0mintegration_status[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;31m#integration status (Sent, Received,...)[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mKeyError[0m: 'IntegrationStatus'
KeyError: 'IntegrationStatus'

