Traceback (most recent call last):
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user01\anaconda3\envs\api-notebooks\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Your status:
status = json_response["Data"]
outbound_financial_document_id = None
#print(json.dumps(json_response, indent=4))

#request status (Queued, Running, Error, Finished)
request_status = json_response["Data"]["AsyncStatus"]

if request_status == "Queued":
    print ("Your request in queue to be processed check the status again in a few seconds...")
if request_status == "Running":
    print ("Your request is runnig check the status again in a few seconds...")
if request_status == "Error":
    print ("Your request has finished with the following errors:")
    error_list=json_response["Data"]["ErrorList"]
    print(error_list)
    print ("Correct the errros and sublit the document again")
elif request_status == "Finished":
    print ("Your request has finished.")
    outbound_financial_document_id = json_response["Data"]["OutboundFinancialDocumentId"]
    print("You have created the outbound document id: " + outbound_financial_document_id)
else:
    print("Your request status: " + request_status);

# the final status Finished and Error
if request_status != "Finished" and request_status != "Error":
    print("Your is not finished yet: " + request_status)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
[1;32m<ipython-input-10-c7201cad54d7>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Your status:[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mstatus[0m [1;33m=[0m [0mjson_response[0m[1;33m[[0m[1;34m"Data"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0moutbound_financial_document_id[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;31m#print(json.dumps(json_response, indent=4))[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mKeyError[0m: 'Data'
KeyError: 'Data'

